spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  datasource:
    url: jdbc:mysql://database-2.cdf03kzemb3t.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username : admin
    password : pre41011
    driver-class-name: com.mysql.cj.jdbc.Driver
config:
  domain: http://seb41-pre-011.s3-website.ap-northeast-2.amazonaws.com/

#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true