insert into member(member_Id, email, name , password, image) values(1, 'abc1@gmail.com', 'kimcoding', 'Code^states1', 'https://avatars.dicebear.com/api/bottts/101.svg');
insert into member(member_Id, email, name , password, image) values(2, 'abc2@gmail.com', 'parkhacker', 'Code^states2', 'https://avatars.dicebear.com/api/bottts/102.svg');
insert into member(member_Id, email, name , password, image) values(3, 'abc3@gmail.com', 'choijava', 'Code^states3', 'https://avatars.dicebear.com/api/bottts/103.svg');
insert into member(member_Id, email, name , password, image) values(4, 'abc4@gmail.com', 'nacode', 'Code^states4', 'https://avatars.dicebear.com/api/bottts/104.svg');
insert into member(member_Id, email, name , password, image) values(5, 'abc5@gmail.com', 'kim10', 'Code^states5', 'https://avatars.dicebear.com/api/bottts/105.svg');
insert into member(member_Id, email, name , password, image) values(6, 'abc6@gmail.com', 'kim11', 'Code^states6', 'https://avatars.dicebear.com/api/bottts/106.svg');
insert into member(member_Id, email, name , password, image) values(7, 'abc7@gmail.com', 'kim12', 'Code^states7', 'https://avatars.dicebear.com/api/bottts/107.svg');
insert into member(member_Id, email, name , password, image) values(8, 'abc8@gmail.com', 'kim13', 'Code^states8', 'https://avatars.dicebear.com/api/bottts/108.svg');
insert into member(member_Id, email, name , password, image) values(9, 'abc9@gmail.com', 'kim14', 'Code^states9', 'https://avatars.dicebear.com/api/bottts/109.svg');
insert into member(member_Id, email, name , password, image) values(10, 'abc10@gmail.com', 'kim15', 'Code^states10', 'https://avatars.dicebear.com/api/bottts/110.svg');
insert into member(member_Id, email, name , password, image) values(11, 'abc11@gmail.com', 'kim16', 'Code^states11', 'https://avatars.dicebear.com/api/bottts/111.svg');
insert into member(member_Id, email, name , password, image) values(12, 'abc12@gmail.com', 'kim17', 'Code^states12', 'https://avatars.dicebear.com/api/bottts/112.svg');
insert into member(member_Id, email, name , password, image) values(13, 'abc13@gmail.com', 'kim18', 'Code^states13', 'https://avatars.dicebear.com/api/bottts/113.svg');
insert into member(member_Id, email, name , password, image) values(14, 'abc14@gmail.com', 'kim19', 'Code^states14', 'https://avatars.dicebear.com/api/bottts/114.svg');
insert into member(member_Id, email, name , password, image) values(15, 'abc15@gmail.com', 'lee10', 'Code^states15', 'https://avatars.dicebear.com/api/bottts/115.svg');
insert into member(member_Id, email, name , password, image) values(16, 'abc16@gmail.com', 'lee11', 'Code^states16', 'https://avatars.dicebear.com/api/bottts/116.svg');
insert into member(member_Id, email, name , password, image) values(17, 'abc17@gmail.com', 'lee12', 'Code^states17', 'https://avatars.dicebear.com/api/bottts/117.svg');
insert into member(member_Id, email, name , password, image) values(18, 'abc18@gmail.com', 'lee13', 'Code^states18', 'https://avatars.dicebear.com/api/bottts/118.svg');
insert into member(member_Id, email, name , password, image) values(19, 'abc19@gmail.com', 'lee14', 'Code^states19', 'https://avatars.dicebear.com/api/bottts/119.svg');
insert into member(member_Id, email, name , password, image) values(20, 'abc20@gmail.com', 'lee15', 'Code^states20', 'https://avatars.dicebear.com/api/bottts/120.svg');
insert into member(member_Id, email, name , password, image) values(21, 'abc21@gmail.com', 'lee16', 'Code^states21', 'https://avatars.dicebear.com/api/bottts/121.svg');
insert into member(member_Id, email, name , password, image) values(22, 'abc22@gmail.com', 'lee17', 'Code^states22', 'https://avatars.dicebear.com/api/bottts/122.svg');
insert into member(member_Id, email, name , password, image) values(23, 'abc23@gmail.com', 'lee18', 'Code^states23', 'https://avatars.dicebear.com/api/bottts/123.svg');
insert into member(member_Id, email, name , password, image) values(24, 'abc24@gmail.com', 'lee19', 'Code^states24', 'https://avatars.dicebear.com/api/bottts/124.svg');
insert into member(member_Id, email, name , password, image) values(25, 'abc25@gmail.com', 'park1', 'Code^states25', 'https://avatars.dicebear.com/api/bottts/125.svg');
insert into member(member_Id, email, name , password, image) values(26, 'abc26@gmail.com', 'park2', 'Code^states26', 'https://avatars.dicebear.com/api/bottts/126.svg');
insert into member(member_Id, email, name , password, image) values(27, 'abc27@gmail.com', 'park3', 'Code^states27', 'https://avatars.dicebear.com/api/bottts/127.svg');
insert into member(member_Id, email, name , password, image) values(28, 'abc28@gmail.com', 'park4', 'Code^states28', 'https://avatars.dicebear.com/api/bottts/128.svg');
insert into member(member_Id, email, name , password, image) values(29, 'abc29@gmail.com', 'park5', 'Code^states29', 'https://avatars.dicebear.com/api/bottts/129.svg');
insert into member(member_Id, email, name , password, image) values(30, 'abc30@gmail.com', 'park6', 'Code^states30', 'https://avatars.dicebear.com/api/bottts/130.svg');
insert into member(member_Id, email, name , password, image) values(31, 'abc31@gmail.com', 'park7', 'Code^states31', 'https://avatars.dicebear.com/api/bottts/131.svg');
insert into member(member_Id, email, name , password, image) values(32, 'abc32@gmail.com', 'park8', 'Code^states32', 'https://avatars.dicebear.com/api/bottts/132.svg');
insert into member(member_Id, email, name , password, image) values(33, 'abc33@gmail.com', 'park9', 'Code^states33', 'https://avatars.dicebear.com/api/bottts/133.svg');
insert into member(member_Id, email, name , password, image) values(34, 'abc34@gmail.com', 'na1', 'Code^states34', 'https://avatars.dicebear.com/api/bottts/134.svg');
insert into member(member_Id, email, name , password, image) values(35, 'abc35@gmail.com', 'na2', 'Code^states35', 'https://avatars.dicebear.com/api/bottts/135.svg');
insert into member(member_Id, email, name , password, image) values(36, 'abc36@gmail.com', 'na3', 'Code^states36', 'https://avatars.dicebear.com/api/bottts/136.svg');
insert into member(member_Id, email, name , password, image) values(37, 'abc37@gmail.com', 'na4', 'Code^states37', 'https://avatars.dicebear.com/api/bottts/137.svg');
insert into member(member_Id, email, name , password, image) values(38, 'abc38@gmail.com', 'na5', 'Code^states38', 'https://avatars.dicebear.com/api/bottts/138.svg');
insert into member(member_Id, email, name , password, image) values(39, 'abc39@gmail.com', 'na6', 'Code^states39', 'https://avatars.dicebear.com/api/bottts/139.svg');
insert into member(member_Id, email, name , password, image) values(40, 'abc40@gmail.com', 'na7', 'Code^states40', 'https://avatars.dicebear.com/api/bottts/140.svg');

insert into tag(tag_Id, name, description, count) values(1, 'java', 'java', 10);
insert into tag(tag_Id, name, description, count) values(2, 'javascript', 'javascript', 11);
insert into tag(tag_Id, name, description, count) values(3, 'python', 'python', 12);
insert into tag(tag_Id, name, description, count) values(4, 'c#', 'c#', 13);
insert into tag(tag_Id, name, description, count) values(5, 'php', 'php', 14);
insert into tag(tag_Id, name, description, count) values(6, 'android', 'android', 15);
insert into tag(tag_Id, name, description, count) values(7, 'html', 'html', 16);
insert into tag(tag_Id, name, description, count) values(8, 'jquery', 'jquery', 17);
insert into tag(tag_Id, name, description, count) values(9, 'c++', 'c++', 18);
insert into tag(tag_Id, name, description, count) values(10, 'mongodb', 'mongodb', 19);
insert into tag(tag_Id, name, description, count) values(11, 'ios', 'ios', 10);
insert into tag(tag_Id, name, description, count) values(12, 'mysql', 'mysql', 11);
insert into tag(tag_Id, name, description, count) values(13, 'sql', 'sql', 12);
insert into tag(tag_Id, name, description, count) values(14, 'node.js', 'node.js', 13);
insert into tag(tag_Id, name, description, count) values(15, 'reactjs', 'reactjs', 14);
insert into tag(tag_Id, name, description, count) values(16, 'arrays', 'arrays', 15);
insert into tag(tag_Id, name, description, count) values(17, 'c', 'c', 16);
insert into tag(tag_Id, name, description, count) values(18, 'asp.net', 'asp.net', 17);
insert into tag(tag_Id, name, description, count) values(19, 'ruby-on-rails', 'ruby-on-rails', 18);
insert into tag(tag_Id, name, description, count) values(20, 'python-3.x', 'python-3.x', 19);
insert into tag(tag_Id, name, description, count) values(21, '.net', '.net', 10);
insert into tag(tag_Id, name, description, count) values(22, 'sql-server', 'sql-server', 11);
insert into tag(tag_Id, name, description, count) values(23, 'swift', 'swift', 12);
insert into tag(tag_Id, name, description, count) values(24, 'django', 'django', 13);
insert into tag(tag_Id, name, description, count) values(25, 'database', 'database', 14);
insert into tag(tag_Id, name, description, count) values(26, 'wordpress', 'wordpress', 15);
insert into tag(tag_Id, name, description, count) values(27, 'excel', 'excel', 16);
insert into tag(tag_Id, name, description, count) values(28, 'pandas', 'pandas', 17);
insert into tag(tag_Id, name, description, count) values(29, 'angularjs', 'angularjs', 18);
insert into tag(tag_Id, name, description, count) values(30, 'regex', 'regex', 19);
insert into tag(tag_Id, name, description, count) values(31, 'ruby', 'ruby', 10);
insert into tag(tag_Id, name, description, count) values(32, 'linux', 'linux', 11);
insert into tag(tag_Id, name, description, count) values(33, 'iphone', 'iphone', 12);
insert into tag(tag_Id, name, description, count) values(34, 'ajax', 'ajax', 13);
insert into tag(tag_Id, name, description, count) values(35, 'xml', 'xml', 14);
insert into tag(tag_Id, name, description, count) values(36, 'vba', 'vba', 15);
insert into tag(tag_Id, name, description, count) values(37, 'typescript', 'typescript', 16);
insert into tag(tag_Id, name, description, count) values(38, 'spring', 'spring', 17);
insert into tag(tag_Id, name, description, count) values(39, 'laravel', 'laravel', 18);
insert into tag(tag_Id, name, description, count) values(40, 'asp.net-mvc', 'asp.net-mvc', 19);